# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'time'

lol = Game.create(name: 'League of Legends', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
dota = Game.create(name: 'Dota 2', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
hots = Game.create(name: 'Heroes of the Storm', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

User.create(name: 'Diego', lastname: 'Martin', email: 'algo@algo.com', password: '1235', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
User.create(name: 'Ale', lastname: 'Lopez', email: 'algo2@algo.com', password: '1235', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

skt = Team.create(description: "Three-time World Champions, two-time Mid-Season Invitational Champions, three time LCK Champions, and inarguably the most dominant team in League of Legends history. SK telecom T1, the reigning World Champions, return to the biggest stage for a chance to defend their title and earn the Summoner’s Cup for the third consecutive time. SSK telecom T1’s qualification casts a shadow over the tournament, as every World Championship they've attended, they’ve won. Although a loss to Longzhu Gaming in the LCK Finals earned them Korea’s #2 seed, SKT's still supplied with more sheer talent and experience than any other roster at Worlds.", image: 'skt1.png', name: 'SKT', origin: 'Korea', coach: 'kkOma', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
ssb = Team.create(description: "Three-time World Champions, two-time Mid-Season Invitational Champions, three time LCK Champions, and inarguably the most dominant team in League of Legends history. SK telecom T1, the reigning World Champions, return to the biggest stage for a chance to defend their title and earn the Summoner’s Cup for the third consecutive time. SSK telecom T1’s qualification casts a shadow over the tournament, as every World Championship they've attended, they’ve won. Although a loss to Longzhu Gaming in the LCK Finals earned them Korea’s #2 seed, SKT's still supplied with more sheer talent and experience than any other roster at Worlds.", image: 'sg.png', name: 'SSB', origin: 'Korea', coach: 'DoGGi', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
ogt = Team.create(description: "Three-time World Champions, two-time Mid-Season Invitational Champions, three time LCK Champions, and inarguably the most dominant team in League of Legends history. SK telecom T1, the reigning World Champions, return to the biggest stage for a chance to defend their title and earn the Summoner’s Cup for the third consecutive time. SSK telecom T1’s qualification casts a shadow over the tournament, as every World Championship they've attended, they’ve won. Although a loss to Longzhu Gaming in the LCK Finals earned them Korea’s #2 seed, SKT's still supplied with more sheer talent and experience than any other roster at Worlds.", image: 'OG.png', name: 'OG', origin: 'España', coach: 'Tanqadin', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
ntt = Team.create(description: "Three-time World Champions, two-time Mid-Season Invitational Champions, three time LCK Champions, and inarguably the most dominant team in League of Legends history. SK telecom T1, the reigning World Champions, return to the biggest stage for a chance to defend their title and earn the Summoner’s Cup for the third consecutive time. SSK telecom T1’s qualification casts a shadow over the tournament, as every World Championship they've attended, they’ve won. Although a loss to Longzhu Gaming in the LCK Finals earned them Korea’s #2 seed, SKT's still supplied with more sheer talent and experience than any other roster at Worlds.", image: 'natus.png', name: 'NATUS', origin: 'Rusia', coach: 'Mrulez', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

a = Player.create(position: 'Top', origin: 'Korea', image: 'fotos/huni.png', name: 'Uno', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Huni', team: Team.where('name' => 'SKT').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
b = Player.create(position: 'Mid', origin: 'Korea', image: 'fotos/blank.png', name: 'Dos', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Blank', team: Team.where('name' => 'SKT').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
c = Player.create(position: 'Jungle', origin: 'Korea', image: 'fotos/faker.png', name: 'Tres', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Faker', team: Team.where('name' => 'SKT').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
d = Player.create(position: 'ADC', origin: 'Korea', image: 'fotos/bang.png', name: 'Cuatro', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Bang', team: Team.where('name' => 'SKT').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
e = Player.create(position: 'Support', origin: 'Korea', image: 'fotos/wolf.png', name: 'Cinco', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Wolf', team: Team.where('name' => 'SKT').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

f = Player.create(position: 'Top', origin: 'Korea', image: 'fotos/bang.png', name: 'Seis', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Acorn', team: Team.where('name' => 'SSB').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
g = Player.create(position: 'Mid', origin: 'Korea', image: 'fotos/bang.png', name: 'Siete', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Spirit', team: Team.where('name' => 'SSB').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
h = Player.create(position: 'Jungle', origin: 'Korea', image: 'fotos/bang.png', name: 'Ocho', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Heart', team: Team.where('name' => 'SSB').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
i = Player.create(position: 'ADC', origin: 'Korea', image: 'fotos/bang.png', name: 'Nueve', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Dade', team: Team.where('name' => 'SSB').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
j = Player.create(position: 'Support', origin: 'Korea', image: 'fotos/bang.png', name: 'Diez', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Deft', team: Team.where('name' => 'SSB').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

k = Player.create(position: 'Top', origin: 'Korea', image: 'fotos/bang.png', name: 'Seis', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Acorn', team: Team.where('name' => 'OG').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
l = Player.create(position: 'Mid', origin: 'Korea', image: 'fotos/bang.png', name: 'Seis', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Acorn', team: Team.where('name' => 'OG').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

m = Player.create(position: 'Top', origin: 'Korea', image: 'fotos/bang.png', name: 'Seis', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Acorn', team: Team.where('name' => 'NATUS').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
n = Player.create(position: 'Mid', origin: 'Korea', image: 'fotos/bang.png', name: 'Seis', biography: 'Faker, as it turns out, is not unbeatable. After finally falling at Worlds 2017, everyone watched as the famed mid laner crumbled into devastation. But his legend is still strong, -- and it’s hard to dispute how strong his individual performances were throughout Worlds. He is the star even among a host of stars as he returns yet again for another All-Star Event.', nick: 'Acorn', team: Team.where('name' => 'NATUS').first, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

aa = Champion.create(name: 'Morgana', game: lol, image: 'fotos/Cassiopeia.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
bb = Champion.create(name: 'Jayce', game: lol, image: 'fotos/Galio.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
cc = Champion.create(name: 'Lee Sin', game: lol, image: 'fotos/Taliyah.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
dd = Champion.create(name: 'Leona', game: lol, image: 'fotos/Cassiopeia.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
ee = Champion.create(name: 'Ezreal', game: lol, image: 'fotos/Galio.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
ff = Champion.create(name: 'Kled', game: lol, image: 'fotos/Taliyah.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
gg = Champion.create(name: 'Darius', game: lol, image: 'fotos/Cassiopeia.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
hh = Champion.create(name: 'Ryze', game: lol, image: 'fotos/Galio.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
ii = Champion.create(name: 'Zed', game: lol, image: 'fotos/Taliyah.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
jj = Champion.create(name: 'Rumble', game: lol, image: 'fotos/Cassiopeia.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
kk = Champion.create(name: 'Vayne', game: lol, image: 'fotos/Galio.png', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

lolmap = Map.create(name: 'Grieta del Invocador', game: lol, image: '/null/', created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

PlayersPick.create(player: a, champion: aa, pick_rate: 5.0, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: a, champion: bb, pick_rate: 2.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: b, champion: cc, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: b, champion: dd, pick_rate: 10.0, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: c, champion: ee, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: c, champion: ff, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: d, champion: gg, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: d, champion: hh, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: e, champion: ii, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: e, champion: jj, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: f, champion: kk, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: f, champion: aa, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: g, champion: bb, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: g, champion: cc, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: h, champion: dd, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: h, champion: ee, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: i, champion: ff, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: i, champion: gg, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: j, champion: hh, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')
PlayersPick.create(player: j, champion: ii, pick_rate: 0.5, win_rate: 0.6, kda: '1:2:3')

PlayersMapPerformance.create(player: a, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: b, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: c, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: d, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: e, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: f, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: g, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: h, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: i, map: lolmap, win_rate: 0.7, loose_rate: 0.3)
PlayersMapPerformance.create(player: j, map: lolmap, win_rate: 0.7, loose_rate: 0.3)

tour = Tournament.create(name: 'Final League of Legends', date: Date.today, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
TournamentTeam.create(tournament: tour, team: skt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
TournamentTeam.create(tournament: tour, team: ssb, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

tour2 = Tournament.create(name: 'Final Dota 2', date: Date.today, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
TournamentTeam.create(tournament: tour2, team: ogt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
TournamentTeam.create(tournament: tour2, team: ntt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

mu = Matchup.create(blue_team: skt, red_team: ssb, winner: skt, looser: ssb, tournament: tour, date: Date.today, :created_at => Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
mu2 = Matchup.create(blue_team: ogt, red_team: ntt, winner: ogt, looser: ntt, tournament: tour2, date: Date.today, :created_at => Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

Bet.create(name: 'Primera sangre para SSB', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'Primera sangre para SKT', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'Gana SKT', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'Gana SSB', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'Gana SKT por 3-0', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'Gana SSB por 3-1', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'El top de SSB tiene un kda de 1:2:3', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')
Bet.create(name: 'El top de SKT tiene un kda de 3:2:1', ratio: 1.4, matchup: mu, refered: 'https://www.betfair.es/sport/basketball')

Statistic.create(ratio: 0.8, name: 'Primera sangre', player: a, team: skt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: b, team: skt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: c, team: skt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: d, team: skt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: e, team: skt, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

Statistic.create(ratio: 0.8, name: 'Primera sangre', player: f, team: ssb, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: g, team: ssb, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: h, team: ssb, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: i, team: ssb, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Statistic.create(ratio: 0.8, name: 'Primera sangre', player: j, team: ssb, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

Streamer.create(image: 'live_final_lol.png', twitch_user_id: 123455, twitch_username: 'OGN Live', twitch_channel_url: 'ognlive', name: 'ognlive', streamer_type: 1, game: lol, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_logiiyt-320x180.jpg', twitch_user_id: 123456, twitch_username: 'imaqtpie', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie1', streamer_type: 2, game: lol, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_stray228-320x180.jpg', twitch_user_id: 123457, twitch_username: 'Streamer3', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie2', streamer_type: 2, game: lol, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_carritoskami-320x180.jpg', twitch_user_id: 123458, twitch_username: 'Streamer4', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie3', streamer_type: 2, game: lol, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_logiiyt-320x180.jpg', twitch_user_id: 123459, twitch_username: 'Streamer5', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie', streamer_type: 3, game: lol, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_stray228-320x180.jpg', twitch_user_id: 123450, twitch_username: 'Streamer6', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie', streamer_type: 3, game: lol, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_carritoskami-320x180.jpg', twitch_user_id: 123451, twitch_username: 'Streamer7', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie', streamer_type: 3, game: hots, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_logiiyt-320x180.jpg', twitch_user_id: 123452, twitch_username: 'Streamer8', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie', streamer_type: 3, game: hots, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_stray228-320x180.jpg', twitch_user_id: 123453, twitch_username: 'Streamer9', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie', streamer_type: 3, game: dota, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_user_carritoskami-320x180.jpg', twitch_user_id: 123454, twitch_username: 'Streamer10', twitch_channel_url: 'https://www.twitch.tv/imaqtpie', name: 'imaqtpie', streamer_type: 3, game: dota, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))
Streamer.create(image: 'live_dota2_final.png', twitch_user_id: 123455, twitch_username: 'ESL Spain', twitch_channel_url: 'eslspain', name: 'eslspain', streamer_type: 1, game: dota, created_at: Time.now.strftime('%d/%m/%Y %H:%M'), updated_at: Time.now.strftime('%d/%m/%Y %H:%M'))

Contact.create(twitchChannel: 'lolete', email: 'alguien@quien.com', message: 'hola, me gustaria estar en la web', dateToPlay: Time.now.strftime('%d/%m/%Y %H:%M'), gender: 1)
